# -*- coding: utf-8 -*-
"""マンホイットニー.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdtHCNKhlNhpKcfwTTeUSzuNC6txLptt
"""

import pandas as pd
from scipy.stats import mannwhitneyu

# エクセルファイルとシート名を指定
excel_file = 'マンホイットニー.xlsx'  # エクセルファイル名を指定
sheet_name = '甘味'          # シート名を指定

# データを読み込む
df = pd.read_excel(excel_file, sheet_name=sheet_name, index_col=0)

# 検定を実行する関数
def perform_mannwhitney_test(dataframe, alpha=0.05):
    groups = dataframe.index.unique()
    results = []

    # 各グループペアで検定を実行
    for i in range(len(groups)):
        for j in range(i + 1, len(groups)):
            group1 = dataframe.loc[groups[i]].dropna().values.flatten()
            group2 = dataframe.loc[groups[j]].dropna().values.flatten()
            # マンホイットニー検定
            stat, p = mannwhitneyu(group1, group2, alternative='two-sided')

            # 有意差の判定
            significant = '有意差あり' if p < alpha else '有意差なし'

            results.append({
                'Group 1': groups[i],
                'Group 2': groups[j],
                'Statistic': stat,
                'P-value': p,
                'Significance': significant
            })
    return results

# マンホイットニー検定を実行
results = perform_mannwhitney_test(df)

# 結果をデータフレームに変換
results_df = pd.DataFrame(results)

# 結果を表示
print(results_df)

# 必要に応じて結果を保存
results_df.to_csv('mannwhitney_results_with_significance.csv', index=False)